# Generated by Django 4.1.6 on 2023-02-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel4app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='photos')),
                ('desc', models.TextField()),
            ],
        ),
    ]
